spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ChessTT
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: #mettre une adresse mail
    password: #mettre un MDP
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
server:
  port: 8080
logging:
  file:
    name: 'log.txt'
    path: '/'
  level:
    root: info